In [1]:
from sympy import S, Eq, sqrt, sin, cos, solve
from sympy.abc import a, b, c, d
import numpy as np


In [2]:
import numpy as np
from scipy.optimize import fsolve
import time


In [39]:

x,y,z = -355.2, 140.9, 16.4
x, y, z = 131.53626779337492, 243.5819537595831, 21.142662119706074

x, y = 300, np.sqrt(406**2 - 300**2)
z = 50

def equations_v(p):
    theta_1, theta_3 = p

    eq1 = 200 * np.sin(theta_1) + 50 * np.cos(theta_1) + 200 * np.sin(theta_3) - np.sqrt(x**2 + y**2)
    eq2 = 200 * np.cos(theta_1) + 50 * np.sin(theta_1) - 200 * np.cos(theta_3) - 70.24 - z

    return [eq1, eq2]

initial_guess = [0, 0] 

solution = fsolve(equations_v, initial_guess)

theta_1, theta_3 = solution
theta_2 = np.pi/2 - theta_1 - theta_3

print(theta_1, theta_2, theta_3)

degree = np.array([theta_1, theta_2, theta_3]) * 180 / np.pi
print(degree)

eq1 = 200 * np.sin(theta_1) + 50 * np.cos(theta_1) + 200 * np.sin(theta_3) - np.sqrt(x**2 + y**2)
eq2 = 200 * np.cos(theta_1) + 50 * np.sin(theta_1) - 200 * np.cos(theta_3) - 70.24 - z

eq1, eq2


1.2696163225401524 -1.3352715404051303 1.6364515446598744
[ 72.74365688 -76.50542377  93.76176689]


/var/folders/hq/747bk1zs2vn857n3rg3jv9nr0000gn/T/ipykernel_28201/4260159270.py:17: RuntimeWarning: The iteration is not making good progress, as measured by the 
 improvement from the last ten iterations.
  solution = fsolve(equations, initial_guess)


(np.float64(-0.6011190530383033), np.float64(-0.03957238448978728))

In [32]:
200 * np.sin(theta_1) + 50 * np.cos(theta_1) + 200 * np.sin(theta_3)

np.float64(406.1158872886499)

In [34]:
200 * np.cos(theta_1) + 50 * np.sin(theta_1) - 200 * np.cos(theta_3) - 70.24

np.float64(21.44008423397125)

In [33]:
np.sqrt(x**2 + y**2)

np.float64(424.26406871192853)

# 

400: threshold


# Case 2

In [44]:

x,y,z = -355.2, 140.9, 16.4
x, y, z = 131.53626779337492, 243.5819537595831, 21.142662119706074

x, y = 300, np.sqrt(406**2 - 300**2)
z = 200

def equations_h(p):
    theta_1, theta_3 = p

    eq1 = 200 * np.sin(theta_1) + 50 * np.cos(theta_1) + 200 * np.sin(theta_3) + 174.15 - np.sqrt(x**2 + y**2)
    eq2 = 200 * np.cos(theta_1) + 50 * np.sin(theta_1) - 200 * np.cos(theta_3) + 103.91 - z

    return [eq1, eq2]

initial_guess = [0, 0] 

solution = fsolve(equations_h, initial_guess)

theta_1, theta_3 = solution
theta_2 = np.pi/2 - theta_1 - theta_3

print(theta_1, theta_2, theta_3)

degree = np.array([theta_1, theta_2, theta_3]) * 180 / np.pi
print(degree)

eq1 = 200 * np.sin(theta_1) + 50 * np.cos(theta_1) + 200 * np.sin(theta_3) + 174.15 - np.sqrt(x**2 + y**2)
eq2 = 200 * np.cos(theta_1) + 50 * np.sin(theta_1) - 200 * np.cos(theta_3) + 103.91 - z

eq1, eq2


0.06400029620748435 0.49872333283046855 1.0080726977569436
[ 3.66694686 28.57474212 57.75831102]


(np.float64(-3.410605131648481e-13), np.float64(3.808509063674137e-12))

# Combine

In [51]:
def equations_v(p):
    theta_1, theta_3 = p

    eq1 = 200 * np.sin(theta_1) + 50 * np.cos(theta_1) + 200 * np.sin(theta_3) - np.sqrt(x**2 + y**2)
    eq2 = 200 * np.cos(theta_1) + 50 * np.sin(theta_1) - 200 * np.cos(theta_3) - 70.24 - z

    return [eq1, eq2]


def equations_h(p):
    theta_1, theta_3 = p

    eq1 = 200 * np.sin(theta_1) + 50 * np.cos(theta_1) + 200 * np.sin(theta_3) + 174.15 - np.sqrt(x**2 + y**2)
    eq2 = 200 * np.cos(theta_1) + 50 * np.sin(theta_1) - 200 * np.cos(theta_3) + 103.91 - z

    return [eq1, eq2]

initial_guess = [0, 0]

sol_v = fsolve(equations_v, initial_guess)
error_v = equations_v(sol_v)

sol_h = fsolve(equations_h, initial_guess)
error_h = equations_h(sol_h)


if np.linalg.norm(error_v) <= np.linalg.norm(error_h):
    theta_0 = np.arctan2(-x, y)
    theta_1, theta_3 = sol_v
    theta_2 = np.pi/2 - theta_1 - theta_3
    theta_4 = theta_0

else:
    theta_0 = np.arctan2(-x, y)
    theta_1, theta_3 = sol_h
    theta_2 = theta_1 + theta_3
    theta_4 = 0
    

print(theta_1, theta_2, theta_3)

degree = np.array([theta_1, theta_2, theta_3]) * 180 / np.pi
print(degree)


0.06400029620748435 1.072072993964428 1.0080726977569436
[ 3.66694686 61.42525788 57.75831102]


/var/folders/hq/747bk1zs2vn857n3rg3jv9nr0000gn/T/ipykernel_28201/2288364781.py:20: RuntimeWarning: The iteration is not making good progress, as measured by the 
 improvement from the last ten iterations.
  sol_v = fsolve(equations_v, initial_guess)


In [50]:
np.linalg.norm(error_v), np.linalg.norm(error_h)

(np.float64(42.28731140287253), np.float64(3.82374993451825e-12))

In [48]:
error_v, error_h

([np.float64(-37.182523662726624), np.float64(-20.141416031508015)],
 [np.float64(-3.410605131648481e-13), np.float64(3.808509063674137e-12)])

In [2]:
import numpy as np
from scipy.linalg import expm, logm
import time

In [12]:
# =====================
# Provided Functions
# =====================

def to_s_matrix(w, v):
    """
    Convert angular velocity w and linear velocity v into a 4x4 matrix in se(3).
    """
    skew_matrix = np.array([
        [    0,   -w[2],  w[1],  v[0]], 
        [ w[2],      0,  -w[0],  v[1]],
        [-w[1],   w[0],      0,  v[2]],
        [    0,      0,      0,     0]
    ])
    return skew_matrix

def FK_pox(joint_angles, m_mat, s_lst):
    """
    Compute the forward kinematics using the product-of-exponentials formulation.
    
    Parameters:
      joint_angles: (n,) vector of joint angles.
      m_mat: 4x4 matrix representing the home configuration.
      s_lst: n x 6 matrix where each row is a screw axis.
      
    Returns:
      A 4x4 homogeneous transformation matrix representing the end-effector pose.
    """
    T = np.eye(4)
    # Our convention here is that s_lst is provided as (n x 6)
    # (the original code transposes s_lst so that each column is a screw)
    # Here we simply loop over the rows.
    for i in range(len(joint_angles)):
        screw_axis = s_lst[i, :]  # 6-vector: first 3 for w, last 3 for v.
        w = screw_axis[:3]
        v = screw_axis[3:]
        S_matrix = to_s_matrix(w, v)
        T = T @ expm(S_matrix * joint_angles[i])
    T = T @ m_mat
    return T

# def get_euler_angles_from_T(T):
#     """
#     Extract Euler angles from the rotation part of T.
    
#     (Note: There are many Euler conventions. Here we simply compute three angles.)
#     """
#     R = T[:3, :3]
#     # Example extraction (this particular extraction may need to be adapted)
#     if -1 <= -R[1, 2] <= 1:
#         theta = np.arcsin(-R[1, 2])
#     else:
#         theta = np.pi/2 if -R[1, 2] > 0 else -np.pi/2

#     if np.isclose(np.abs(theta), np.pi / 2):
#         phi = 0
#         psi = np.arctan2(R[0, 1], R[0, 0])
#     else:
#         psi = np.arctan2(R[0, 1], R[0, 0])
#         phi = np.arctan2(R[2, 2], R[0, 2])

#     return [phi - np.pi/2, theta, psi]

def get_euler_angles_from_T(T):
    """
    Extract Z-Y-Z Euler angles from 4x4 transformation matrix.
    Returns: alpha (first Z), beta (Y), gamma (second Z) in radians
    """
    R = T[:3, :3]
    
    # Handle gimbal lock case when beta = 0 or pi
    if np.abs(R[2, 2]) >= 1.0 - 1e-12:
        # Gimbal lock: beta = 0 or pi
        beta = 0 if R[2, 2] > 0 else np.pi
        # In gimbal lock, alpha + gamma = atan2(R[1,0], R[0,0]) for beta=0
        # or alpha - gamma = atan2(R[1,0], R[0,0]) for beta=pi
        alpha = np.arctan2(R[1, 0], R[0, 0])
        gamma = 0  # Choose gamma = 0 in gimbal lock
    else:
        beta = np.arccos(R[2, 2])
        alpha = np.arctan2(R[1, 2], R[0, 2])
        gamma = np.arctan2(R[2, 1], -R[2, 0])
        
    return alpha, beta, gamma


def get_pose_from_T(T):
    """
    Extract the 6DOF pose vector (position and Euler angles) from T.
    """
    xyz = T[:3, 3]
    [yaw, pitch, roll] = get_euler_angles_from_T(T)
    pose = np.hstack((xyz, [yaw, pitch, roll]))
    return pose

# Define the home configuration (M matrix) as provided.
M_matrix = np.array([
    [1.0, 0.0, 0.0,   0.0],
    [0.0, 1.0, 0.0, 424.15],
    [0.0, 0.0, 1.0, 303.91],
    [0.0, 0.0, 0.0,   1.0]
])

# Define the screw axes (each row is a screw axis: [w1, w2, w3, v1, v2, v3]).
S_list = np.array([
    [ 0.0,  0.0, 1.0,    0.0,     0.0,    0.0],
    [-1.0,  0.0, 0.0,    0.0, -103.91,    0.0],
    [-1.0,  0.0, 0.0,    0.0, -303.91,   50.0],
    [-1.0,  0.0, 0.0,    0.0, -303.91,  250.0],
    [ 0.0,  1.0, 0.0, -303.91,    0.0,    0.0]
])


pos = [0, 0, 0, 0, 0]
pos = [-0.714835, 0.53075737, -0.09203, 0.9802, 0.2040]
pos = [-1.6551, 0.12732, 0.552233, 0.8973788, 0.21629]

pos = [-0.714835, 0.53075737, -0.09203, 0.9802, 0.2040]
pos = [-0.714835, 0.12732, 0.552233, 0.8973788, 0.21629]

ee_T = FK_pox(pos, M_matrix, S_list)
ee_pose = get_pose_from_T(ee_T)
ee_pose[:].round(3)

print(ee_pose[0] / ee_pose[1])

ee_pose[:].round(2)


0.8679708626239804


array([150.43, 173.31,  -3.89,   0.64,   1.58,  -1.57])

In [197]:
np.arctan2(-ee_pose[0], ee_pose[1])

np.float64(-0.7148350000000001)

In [410]:

# =====================
# New Helper Functions for IK
# =====================

def adjoint(T):
    """
    Compute the 6x6 adjoint representation of a transformation matrix T.
    
    The adjoint maps a twist expressed in one frame to a twist expressed in another.
    """
    R = T[:3, :3]
    p = T[:3, 3]
    p_skew = np.array([
        [   0,   -p[2],  p[1]],
        [ p[2],      0, -p[0]],
        [-p[1],   p[0],     0]
    ])
    adj_T = np.zeros((6, 6))
    adj_T[:3, :3] = R
    adj_T[3:, :3] = p_skew @ R
    adj_T[3:, 3:] = R
    return adj_T

def compute_jacobian(joint_angles, s_lst):
    """
    Compute the spatial Jacobian for the current configuration.
    
    Parameters:
      joint_angles: (n,) current joint angles.
      s_lst: n x 6 matrix of screw axes.
      
    Returns:
      J: 6 x n Jacobian matrix.
    """
    n = len(joint_angles)
    J = np.zeros((6, n))
    T = np.eye(4)
    for i in range(n):
        # For the i-th joint, map the screw axis into the current frame:
        screw = s_lst[i, :]   # (6,)
        J[:, i] = adjoint(T) @ screw
        # Update T by “moving” along the i-th joint’s motion:
        S_matrix = to_s_matrix(screw[:3], screw[3:])
        T = T @ expm(S_matrix * joint_angles[i])
    return J

def se3_to_vec(se3mat):
    """
    Convert a 4x4 se(3) matrix into a 6-vector (the vee operator).
    
    The se(3) matrix is assumed to have the form:
      [ 0    -w3   w2   v1 ]
      [ w3    0   -w1   v2 ]
      [-w2   w1    0    v3 ]
      [ 0     0    0     0 ]
    and returns the 6-vector: [w1, w2, w3, v1, v2, v3].
    """
    # Ensure we work with real numbers (logm may return small imaginary parts)
    se3mat = np.real(se3mat)
    w = np.array([se3mat[2, 1], se3mat[0, 2], se3mat[1, 0]])
    v = np.array([se3mat[0, 3], se3mat[1, 3], se3mat[2, 3]])
    return np.concatenate((w, v))

# =====================
# Inverse Kinematics Function
# =====================

def IK_pox(T_desired, m_mat, s_lst, initial_guess=None, tol=1e-3, max_iterations=1000, alpha=0.1):
    """
    Compute the inverse kinematics for the given end-effector transformation using
    an iterative, Jacobian-based approach.
    
    Parameters:
      T_desired: 4x4 homogeneous transformation matrix representing the desired pose.
      m_mat: 4x4 home configuration matrix.
      s_lst: n x 6 matrix of screw axes.
      initial_guess: (n,) vector of initial joint angles (if None, zeros are used).
      tol: Tolerance for the norm of the error twist.
      max_iterations: Maximum number of iterations.
      alpha: Step size (gain) for the update.
      
    Returns:
      joint_angles: (n,) vector of joint angles that (approximately) achieve T_desired.
    """
    n = s_lst.shape[0]  # number of joints
    if initial_guess is None:
        joint_angles = np.zeros(n)
    else:
        joint_angles = initial_guess.copy()

    for i in range(max_iterations):
        # 1. Compute the current end-effector transformation.
        T_current = FK_pox(joint_angles, m_mat, s_lst)
        
        # 2. Compute the error transformation:
        # T_error = np.linalg.inv(T_current) @ T_desired
        T_error = T_desired @ np.linalg.inv(T_current)
        # 3. Compute the error twist (as a 6-vector) via the matrix logarithm.
        error_se3 = logm(T_error)
        error_twist = se3_to_vec(error_se3)
        
        # Check if the error is small enough:
        error_norm = np.linalg.norm(error_twist)
        if error_norm < tol:
            print(f"Converged in {i} iterations with error norm {error_norm:.6f}.")
            return joint_angles
        
        # 4. Compute the spatial Jacobian at the current joint angles.
        J = compute_jacobian(joint_angles, s_lst)  # shape: 6 x n
        
        # 5. Compute a change in joint angles (delta_theta) using the pseudoinverse.
        delta_theta = alpha * np.linalg.pinv(J) @ error_twist
        
        # 6. Update the joint angles.
        joint_angles = joint_angles + delta_theta
        
    print("Warning: IK did not converge within the maximum number of iterations.")
    return joint_angles

# =====================
# Example Usage
# =====================

# Suppose we have a desired end-effector transformation T_desired.
# (In practice, T_desired could be obtained from a pose-planning algorithm or sensor feedback.)
# For demonstration, let’s assume T_desired is computed from some "true" joint angles.

true_joint_angles = [0, 0, 0, 0, 0]
true_joint_angles = [-0.714835, 0.53075737, -0.09203, 0.9802, 0.2040]
# true_joint_angles = [-1.6551, 0.12732, 0.552233, 0.8973788, 0.21629]

T_desired = FK_pox(true_joint_angles, M_matrix, S_list)
desired_ee_pose = get_pose_from_T(T_desired)
desired_ee_pose = np.array([-355.2,    140.9 ,    16.4 ,     1.193,    0.   ,   -0.   ])
T_desired = euler_to_transformation_matrix(-355.2,    140.9 ,    16.4 ,     1.193,    0.   ,   -0.   )


# Now, we can use our inverse kinematics function to recover the joint angles.
initial_guess = np.zeros(5)  # starting from zero for all joints
solved_joint_angles = IK_pox(T_desired, M_matrix, S_list, initial_guess, tol=1e-3, max_iterations=1000, alpha=0.1)

print("True joint angles (radians):")
print(true_joint_angles)
print("Solved joint angles (radians):")
print(solved_joint_angles)

# Optionally, verify by computing the forward kinematics from the solved joint angles:
start_time = time.time()
T_solved = FK_pox(solved_joint_angles, M_matrix, S_list)

print("Error between desired and solved transformation:")
print(np.linalg.norm(T_desired - T_solved))

print("\nTime taken to compute FK: ", time.time() - start_time, " seconds")


# testing
print("\nTesting")
ee_pose_solved = get_pose_from_T(T_solved)
print("Desired end-effector pose:")
print(desired_ee_pose.round(3))

print("Solved end-effector pose:")
print(ee_pose_solved.round(3))

# solved_joint_angles

True joint angles (radians):
[-0.714835, 0.53075737, -0.09203, 0.9802, 0.204]
Solved joint angles (radians):
[ 1.193       0.76483406  0.63808933 -1.40292339  0.00364648]
Error between desired and solved transformation:
0.060246046240541175

Time taken to compute FK:  0.00012421607971191406  seconds

Testing
Desired end-effector pose:
[-355.2    140.9     16.4      1.193    0.      -0.   ]
Solved end-effector pose:
[-3.55178e+02  1.40956e+02  1.64000e+01 -1.00000e-03 -3.00000e-03
 -1.19300e+00]


## Error Tolerance 

In [412]:
import numpy as np
from scipy.linalg import logm, expm

# (Assume to_s_matrix, FK_pox, and other helper functions are defined above)

def wrap_angle(angle, lower=-np.pi/2, upper=np.pi/2):
    """Wrap an angle into the interval [lower, upper] by adding/subtracting 2*pi."""
    while angle > upper:
        angle -= 2 * np.pi
    while angle < lower:
        angle += 2 * np.pi
    return angle

def IK_pox_translation_only(T_desired, m_mat, s_lst, initial_guess=None, tol=1e-3, max_iterations=1000, alpha=0.1):
    """
    Inverse kinematics that only considers the x, y, z (translation) components of the error.
    
    Parameters:
      T_desired: 4x4 homogeneous transformation matrix for the desired pose.
      m_mat: 4x4 home configuration matrix.
      s_lst: n x 6 matrix of screw axes.
      initial_guess: (n,) vector of initial joint angles (default is zeros).
      tol: Tolerance on the translational error norm.
      max_iterations: Maximum iterations for the solver.
      alpha: Step size for the update.
    
    Returns:
      joint_angles: (n,) vector of joint angles (each wrapped to [-pi/2, pi/2]).
    """
    n = s_lst.shape[0]  # number of joints
    if initial_guess is None:
        joint_angles = np.zeros(n)
    else:
        joint_angles = initial_guess.copy()

    for iteration in range(max_iterations):
        # 1. Compute current end-effector transformation.
        T_current = FK_pox(joint_angles, m_mat, s_lst)
        
        # 2. Compute the error transformation.
        T_error = T_desired @ np.linalg.inv(T_current)
        
        # 3. Compute the error twist (6x1 vector) using the matrix logarithm.
        error_se3 = logm(T_error)
        error_twist = se3_to_vec(error_se3)
        
        # 4. Extract only the translational error (x,y,z)
        error_translation = error_twist[3:]
        error_norm = np.linalg.norm(error_translation)
        
        if error_norm < tol:
            print(f"Converged in {iteration} iterations with translation error norm {error_norm:.6f}.")
            # Wrap joint angles before returning
            joint_angles = np.array([wrap_angle(theta) for theta in joint_angles])
            return joint_angles
        
        # 5. Compute the full spatial Jacobian and then take only its translation part.
        J = compute_jacobian(joint_angles, s_lst)  # 6 x n
        J_translation = J[3:, :]  # only the last 3 rows (translational part)
        
        # 6. Compute change in joint angles using the pseudoinverse.
        delta_theta = alpha * np.linalg.pinv(J_translation) @ error_translation
        
        # 7. Update joint angles.
        joint_angles = joint_angles + delta_theta
        
        # 8. (Optional) Wrap the joint angles after each update:
        joint_angles = np.array([wrap_angle(theta) for theta in joint_angles])
    
    print("Warning: IK did not converge within the maximum number of iterations.")
    # Wrap before returning the final joint angles.
    joint_angles = np.array([wrap_angle(theta) for theta in joint_angles])
    return joint_angles

# Suppose we have a desired end-effector transformation T_desired.
# (In practice, T_desired could be obtained from a pose-planning algorithm or sensor feedback.)
# For demonstration, let’s assume T_desired is computed from some "true" joint angles.

true_joint_angles = [0, 0, 0, 0, 0]
true_joint_angles = [-0.714835, 0.53075737, -0.09203, 0.9802, 0.2040]
# true_joint_angles = [-1.6551, 0.12732, 0.552233, 0.8973788, 0.21629]

T_desired = FK_pox(true_joint_angles, M_matrix, S_list)
desired_ee_pose = get_pose_from_T(T_desired)
desired_ee_pose = np.array([-355.2,    140.9 ,    16.4 ,     1.193,    0.   ,   -0.   ])
T_desired = euler_to_transformation_matrix(-355.2,    140.9 ,    16.4 ,     1.193,    0.   ,   -0.   )


# Now, we can use our inverse kinematics function to recover the joint angles.
initial_guess = np.zeros(5)  # starting from zero for all joints
solved_joint_angles = IK_pox_translation_only(T_desired, M_matrix, S_list, initial_guess, tol=1e-3, max_iterations=1000, alpha=0.1)

print("True joint angles (radians):")
print(true_joint_angles)
print("Solved joint angles (radians):")
print(solved_joint_angles)

# Optionally, verify by computing the forward kinematics from the solved joint angles:
start_time = time.time()
T_solved = FK_pox(solved_joint_angles, M_matrix, S_list)

print("Error between desired and solved transformation:")
print(np.linalg.norm(T_desired - T_solved))

print("\nTime taken to compute FK: ", time.time() - start_time, " seconds")


# testing
print("\nTesting")
ee_pose_solved = get_pose_from_T(T_solved)
print("Desired end-effector pose:")
print(desired_ee_pose.round(3))

print("Solved end-effector pose:")
print(ee_pose_solved.round(3))

# solved_joint_angles

Converged in 123 iterations with translation error norm 0.000975.
True joint angles (radians):
[-0.714835, 0.53075737, -0.09203, 0.9802, 0.204]
Solved joint angles (radians):
[ 0.          0.64185991  0.70150417 -1.45429033  0.00362369]
Error between desired and solved transformation:
429.1254115368992

Time taken to compute FK:  0.00013017654418945312  seconds

Testing
Desired end-effector pose:
[-355.2    140.9     16.4      1.193    0.      -0.   ]
Solved end-effector pose:
[ 0.00000e+00  3.77961e+02  5.86010e+01 -4.00000e-03  1.11000e-01
  0.00000e+00]


In [14]:
import numpy as np
from scipy.linalg import expm
from scipy.optimize import minimize
import time


In [15]:

# ---------------------------------------------------
# 1. Transformation Matrix Builder
# ---------------------------------------------------
def euler_to_transformation_matrix(x, y, z, yaw, pitch, roll):
    """
    Build a 4x4 homogeneous transformation matrix from the position (x,y,z)
    and Euler angles (yaw, pitch, roll) using the sequence:
    
       R = R_z(yaw) * R_x(pitch) * R_y(roll)
    
    This is chosen for the coordinate system:
      - x: right
      - y: front
      - z: up
      
    The yaw is a rotation about the z axis.
    """
    # Rotation about z (yaw)
    Rz = np.array([
        [np.cos(yaw), -np.sin(yaw), 0],
        [np.sin(yaw),  np.cos(yaw), 0],
        [0,           0,            1]
    ])
    # Rotation about x (pitch)
    Rx = np.array([
        [1,          0,           0],
        [0, np.cos(pitch), -np.sin(pitch)],
        [0, np.sin(pitch),  np.cos(pitch)]
    ])
    # Rotation about y (roll)
    Ry = np.array([
        [ np.cos(roll), 0, np.sin(roll)],
        [0,             1, 0],
        [-np.sin(roll), 0, np.cos(roll)]
    ])
    R = Rz @ Rx @ Ry
    T = np.eye(4)
    T[:3, :3] = R
    T[:3, 3] = [x, y, z]
    return T

# ---------------------------------------------------
# 2. Inverse of the Above: Extract Euler Angles from T
# ---------------------------------------------------
def get_euler_angles_from_T(T):
    """
    Extract Euler angles [yaw, pitch, roll] from the rotation part of T.
    
    For a rotation defined as R = R_z(yaw)*R_x(pitch)*R_y(roll), one valid extraction is:
    
      pitch = asin(R[2,1])
      yaw   = arctan2(-R[0,1], R[1,1])
      roll  = arctan2(-R[2,0], R[2,2])
    
    These formulas assume that the rotations are small enough so that no singularity is hit.
    """
    R = T[:3, :3]
    pitch = np.arcsin(R[2, 1])
    yaw   = np.arctan2(-R[0, 1], R[1, 1])
    roll  = np.arctan2(-R[2, 0], R[2, 2])
    return [yaw, pitch, roll]

def get_pose_from_T(T):
    """
    Return a 6-element pose vector: [x, y, z, yaw, pitch, roll].
    """
    xyz = T[:3, 3]
    euler = get_euler_angles_from_T(T)
    return np.hstack((xyz, euler))

# ---------------------------------------------------
# 3. Forward Kinematics Functions (Product-of-Exponentials)
# ---------------------------------------------------
def to_s_matrix(w, v):
    """
    Given angular velocity w and linear velocity v,
    return the corresponding 4x4 matrix in se(3).
    """
    skew_matrix = np.array([
        [    0, -w[2],  w[1], v[0]],
        [ w[2],     0, -w[0], v[1]],
        [-w[1],  w[0],     0, v[2]],
        [    0,     0,     0,    0]
    ])
    return skew_matrix

def FK_pox(joint_angles, m_mat, s_lst):
    """
    Compute the forward kinematics using the product-of-exponentials formulation.
    """
    T = np.eye(4)
    for i in range(len(joint_angles)):
        screw_axis = s_lst[i, :]  # [w1, w2, w3, v1, v2, v3]
        w = screw_axis[:3]
        v = screw_axis[3:]
        S = to_s_matrix(w, v)
        T = T @ expm(S * joint_angles[i])
    T = T @ m_mat
    return T

# ---------------------------------------------------
# 4. Robot Parameters
# ---------------------------------------------------
# Home configuration matrix (M)
M_matrix = np.array([
    [1.0, 0.0, 0.0,   0.0],
    [0.0, 1.0, 0.0, 424.15],
    [0.0, 0.0, 1.0, 303.91],
    [0.0, 0.0, 0.0,   1.0]
])

# Screw axes for each joint (each row: [w1, w2, w3, v1, v2, v3])
S_list = np.array([
    [ 0.0,  0.0,  1.0,    0.0,     0.0,    0.0],
    [-1.0,  0.0,  0.0,    0.0, -103.91,    0.0],
    [-1.0,  0.0,  0.0,    0.0, -303.91,   50.0],
    [-1.0,  0.0,  0.0,    0.0, -303.91,  250.0],
    [ 0.0,  1.0,  0.0, -303.91,     0.0,    0.0]
])
# (This example assumes a 5-DOF robot.)

# ---------------------------------------------------
# 5. IK Solver with Fixed Base Yaw
# ---------------------------------------------------
def IK_with_fixed_base_yaw(target_x, target_y, target_z, target_pitch, target_roll, num_starts=500000):
    """
    For a robot whose first (base) joint is the only one that can affect yaw,
    compute the required base yaw from the target x,y position. Then build a
    desired transformation with that yaw, and solve for the remaining joints so
    that the end-effector achieves the target translation and pitch.
    
    Parameters:
      target_x, target_y, target_z : desired translation (in mm or units consistent with M_matrix)
      target_pitch, target_roll     : desired pitch and roll (in radians)
      num_starts                    : number of random initial guesses
      
    Returns:
      q_full       : Full joint-angle vector (with the base joint fixed).
      best_obj     : Best achieved objective value.
      base_yaw     : The computed (and fixed) base yaw.
      T_desired_new: The desired transformation (with base yaw applied).
    """
    n = S_list.shape[0]  # Total number of joints (here, 5)
    
    # Compute the required base yaw from target x and y.
    base_yaw = np.arctan2(-target_x, target_y)
    
    # Build the desired transformation with the computed base yaw.
    # (Here, we use the given target translation and the desired pitch/roll.)
    T_desired_new = euler_to_transformation_matrix(target_x, target_y, target_z,
                                                   base_yaw, target_pitch, target_roll)
    desired_pose = get_pose_from_T(T_desired_new)
    
    # We will optimize only the remaining (n-1) joints.
    def objective(q_free):
        # Construct the full joint vector: first joint is fixed to base_yaw.
        q_full = np.hstack(([base_yaw], q_free))
        T_current = FK_pox(q_full, M_matrix, S_list)
        current_pose = get_pose_from_T(T_current)
        # We care about translation (x, y, z) and pitch (index 4) only.
        error = np.array([
            current_pose[0] - desired_pose[0],
            current_pose[1] - desired_pose[1],
            current_pose[2] - desired_pose[2],
            current_pose[4] - desired_pose[4]
        ])
        # Use heavy weighting on translation and pitch.
        weights = np.array([150.0, 150.0, 150.0, 100.0])
        return np.sum((weights * error) ** 2)
    
    # Optimize over the remaining joints with loose bounds.
    bounds = [(-np.pi/2, np.pi/2)] * (n - 1)
    
    best_sol = None
    best_obj = np.inf
    for i in range(num_starts):
        q0 = np.random.uniform(-np.pi, np.pi, size=n - 1)
        res = minimize(objective, q0, method='SLSQP', bounds=bounds,
                       options={'ftol': 8e-9, 'maxiter': 1000})
        q_full = np.hstack(([base_yaw], res.x.copy()))
        z = get_pose_from_T(FK_pox(q_full, M_matrix, S_list))[2]
        if np.isfinite(res.fun) and res.fun < best_obj and z > 5:
            best_obj = res.fun
            best_sol = res.x.copy()
    
    if best_sol is None:
        return None, best_obj, base_yaw, T_desired_new
    else:
        q_full = np.hstack(([base_yaw], best_sol))
        return q_full, best_obj, base_yaw, T_desired_new

# ---------------------------------------------------
# 6. Test the Solver
# ---------------------------------------------------
# Specify the target: note that here x (right) is negative means to the left,
# y (front) is positive, and z is up.
target_x = -355.2
target_y = 140.9
target_z = 16.4
target_pitch = 0   # in radians
target_roll  = 0   # in radians

start_time = time.time()
solution, obj_val, base_yaw, T_desired_new = IK_with_fixed_base_yaw(
    target_x, target_y, target_z, target_pitch, target_roll, num_starts=1000)
elapsed = time.time() - start_time

print("Target translation: ({}, {}, {})".format(target_x, target_y, target_z))
print("Computed base yaw (fixed): {:.4f} rad".format(base_yaw))
print("\nDesired Transformation Matrix (with fixed base yaw):")
print(np.round(T_desired_new, 3))
if solution is not None:
    print("\nSolution (joint angles):")
    print(np.round(solution, 5))
    T_sol = FK_pox(solution, M_matrix, S_list)
    sol_pose = get_pose_from_T(T_sol)
    desired_pose = get_pose_from_T(T_desired_new)
    print("\nAchieved Pose:", np.round(sol_pose, 3))
    print("Desired Pose :", np.round(desired_pose, 3))
    err_vec = np.array([
        sol_pose[0] - desired_pose[0],
        sol_pose[1] - desired_pose[1],
        sol_pose[2] - desired_pose[2],
        sol_pose[4] - desired_pose[4], 
    ])
    print("Error norm (translation & pitch):", np.linalg.norm(err_vec))
    print("Objective value:", obj_val)

else:
    print("No solution found, best objective value:", obj_val)
print("Elapsed time: {:.4f} seconds".format(elapsed))


Target translation: (-355.2, 140.9, 16.4)
Computed base yaw (fixed): 1.1932 rad

Desired Transformation Matrix (with fixed base yaw):
[[   0.369   -0.93     0.    -355.2  ]
 [   0.93     0.369    0.     140.9  ]
 [   0.       0.       1.      16.4  ]
 [   0.       0.       0.       1.   ]]

Solution (joint angles):
[ 1.19316  0.87504  0.41614 -1.5708   1.49699]

Achieved Pose: [-3.79387e+02  1.50495e+02  4.95550e+01  1.19300e+00  2.80000e-01
  1.49700e+00]
Desired Pose : [-355.2    140.9     16.4      1.193    0.      -0.   ]
Error norm (translation & pitch): 42.17433554873176
Objective value: 39968778.944448285
Elapsed time: 11.8637 seconds


In [408]:
359.049 / 142.4

np.tan(-355.2 / 140.9)

np.float64(0.7148995381879585)